/*
 * Copyright (C) 2020 Luke Klinker
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

def props = new Properties()
def propsFile = project.file('keystore.properties')

if (propsFile.exists()) {
    props.load(new FileInputStream(propsFile))
}

def apiKeys = new Properties()
def apiFile = rootProject.file('api_keys.properties')

if (apiFile.exists()) {
    apiKeys.load(new FileInputStream(apiFile))
}

buildscript {

    ext.buildInfo = [
            'id'   : 'xyz.klinker.messenger',
            'name' : '5.4.6',
            'number': System.getenv("BUILD_NUMBER") as Integer ?: 135,
    ]

    ext.versions = [
            'gradlePlugin'     : '4.1.0',
            'targetSdk'        : 30,
            'minSdk'           : 21,
            'kotlin'           : '1.4.10',

            'playServices'     : '17.0.0',
            'glide'            : '4.11.0',
            'retrofit'         : '2.7.2',

            'androidX'         : '1.0.0',
            'androidXExif'     : '1.2.0',
            'androidXTester'   : '1.1.0',
            'androidXEspresso' : '3.1.0',

            'firebaseAnalytics': '17.4.4',
            'firebaseMessaging': '20.2.0',
            'firebaseStorage'  : '19.1.1',
            'firebaseAuth'     : '19.3.2',

            'mockito'          : '3.5.13',
            'robolectric'      : '4.4',
            'testEspresso'     : '3.0.1',
            'testRunner'       : '1.0.1',
    ]

    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:${versions.gradlePlugin}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${versions.kotlin}"
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
    }
}

allprojects {

    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://dl.bintray.com/drummer-aidan/maven" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        flatDir { dirs "$rootProject.projectDir/shared/libs" }
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {

            android {
                compileSdkVersion versions.targetSdk

                defaultConfig {
                    targetSdkVersion versions.targetSdk

                    vectorDrawables.useSupportLibrary = true
                    multiDexEnabled true

                    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

                    buildConfigField("String", "GIPHY_API_KEY",
                            "\"${apiKeys.getProperty('GIPHY', '')}\"")

                    buildConfigField("String", "ARTICLE_API_KEY",
                            "\"${apiKeys.getProperty('ARTICLE', '')}\"")

                    buildConfigField("String", "YOUTUBE_API_KEY",
                            "\"${apiKeys.getProperty('YOUTUBE', '')}\"")
                }

                signingConfigs {
                    debug {
                        storeFile file("debug.keystore")
                        storePassword "android"
                        keyAlias "androiddebugkey"
                        keyPassword "android"
                    }

                    release {
                        if (propsFile.exists()) {
                            storeFile file(props['keystorefile'])
                            storePassword props['keystorepassword']
                            keyAlias props['keyalias']
                            keyPassword props['keypassword']
                        }
                    }
                }

                buildTypes {
                    debug {
                        versionNameSuffix "-DEBUG"
                        signingConfig signingConfigs.debug
                    }

                    release {
                        signingConfig signingConfigs.release
                    }
                }

                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_1_8
                    targetCompatibility JavaVersion.VERSION_1_8
                }

                packagingOptions {
                    exclude 'META-INF/DEPENDENCIES'
                    exclude 'META-INF/LICENSE'
                    exclude 'META-INF/NOTICE'
                }
            }
        }
    }
}
